### ISSUE TITLE
Wrong link in Lab 3

### ISSUE THREAD

**Issue by JamesHusband** [nrwl/nx-react-workshop#2]
The link for example .scss is incorrect.

[https://github.com/nrwl/nx-react-workshop/blob/main/examples/lab2/apps/store/src/app/app.scss](https://github.com/nrwl/nx-react-workshop/blob/main/examples/lab2/apps/store/src/app/app.scss)

should be 

[https://raw.githubusercontent.com/nrwl/nx-react-workshop/main/examples/lab2/apps/store/src/app/app.module.scss](https://raw.githubusercontent.com/nrwl/nx-react-workshop/main/examples/lab2/apps/store/src/app/app.module.scss)

**Comment by meeroslav** [comment]
Solved!
